spring:
  application:
    name: micor-zuul
server:
  port: 6001
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

zuul:
  routes:
    micor-zuul.path: /api/**
    micor-zuul.url: "forward:/local"
    orient-service-url:                          #面向服务的路由配置,此名称可以自定义
      path: /zuul-order/**
      service-id: micro-consumer-order-feign

  retryable: true
ribbon:
  # 开启重试
  connectTimeout: 300
  # 请求连接的超时时间 ms
  readTimeout: 300
  # 请求处理的超时时间 ms
  maxAutoRetries: 3
  # 对当前实例的重试次数
  maxAutoRetriesNextServer: 3
  # 对所有操作请求都进行重试
  okToRetryOnAllOperations: true