server:
  port: 7902
spring:
  application:
    name: micro-user
eureka:
  server:
    port: 8761
  instance:
    hostname: peer1
    metadata-map:
      company: izk
      localtion: bj
  client:
    healthcheck:
      #只可以配置在application.yml中
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.server.port}/eureka

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true